language: ruby
rvm:
  - 2.2

install:
  - gem install jekyll jekyll-paginate html-proofer

script:
  - rake build
  - rake test

branches:
  only:
    - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true   # speeds up installation of html-proofer
