# Site settings
title: ActWise
tagline: A minimalistic blog
email: thomas@actwise.de
description: > # this means to ignore newlines until "baseurl"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.actwise.de" # the base hostname & protocol for your site
twitter_username: h0lz0hr
#github_username:  andrewcodes
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments

# Gems
gems: [jekyll-paginate]
